### ISSUE TITLE
Create VM VSTS task reports success even if artifacts fail

### ISSUE THREAD

**Issue by gregpakes** [Azure/azure-devtestlab#167]
If you are using the Create VM task in VSTS and one or more of the artifacts fails, the task still reports successful to VSTS.

I would expect it to fail the build/release.

**Comment by leovms** [comment]
This is by design, a the VM creation process in fact succeeds. If it fails to apply artifacts there's nothing reported back to the calling process to indicate the creation failed. If you apply artifacts via UI or via the API, you will see that a failing artifact does not mark the VM as failed.

Having said that, it may be a useful feature to add to the task to inspect the artifact provisioning state and act accordingly. For example, some may want this to fail the task, as you are describing.

**Comment by leovms** [comment]
This feature is now available in the latest version of the [Azure DevTest Labs Tasks](https://marketplace.visualstudio.com/items?itemName=ms-azuredevtestlabs.tasks).
