### ISSUE TITLE
BYOT - How to install Artifacts?

### ISSUE THREAD

**Issue by tarunaroraonline** [Azure/azure-devtestlab#256]
I can't figure out how I can use artifacts when I am using my own ARM template. Is it possible?

I am currently doing domain join, installing BGInfo and running a custom powershell script as a custom extension. I want to now install the VSTS Agent on this host, how can i do this in my ARM template?

Tarun

**Comment by tarunaroraonline** [comment]
Any thoughts?

**Comment by ajay-arora** [comment]
Applying artifacts via RestAPI is a HTTP Post action on labs/virtualmachines/applyartifacts.
Making POST calls via ARM template is not possible.

**Comment by ajay-arora** [comment]
There is a workaround though. We allow you to apply artifacts while creating a LabVM. And creating a LabVM is a PUT, and thus possible via ARM template. 
Here is RestAPI reference : https://docs.microsoft.com/en-us/rest/api/dtl/virtualmachines

**Comment by tarunaroraonline** [comment]
Do you have a code snippet to hand?

**Comment by ericame** [comment]
Hi Tarun,

We currently don't provide a sample, but you can generate an arm template for creating a VM with artifacts via the portal UI and save it following these steps:
1. Navigate to your lab.
1. Click +Add at the top of the Overview blade to add VM.
1. Choose a base image.
1. Fill out the required fields.
1. Click on Artifacts and add the artifacts that you want to install.
1. When you're done, click View ARM Template. From the new blade that opens, you can do CTRL-A to select the template and CTRL-C to copy it so that you can save it to a local file.
