### ISSUE TITLE
New Join Domain Artifact - "A specified logon session does not exist. It may already have been terminated."

### ISSUE THREAD

**Issue by chrispont** [Azure/azure-devtestlab#291]
Hi,

The New Join Domain Artifact seems to be unable to join my domain and throws the following error - "A specified logon session does not exist. It may already have been terminated."

The domain controller is at the end of an IPSec tunnel (via newtwork gateway) but I can remote from my DevTestLabs machine onto the domain controller (so connectivity seems to be fine). I've also managed to join the domain manually by remoting onto the box.

Any ideas?

Many Thanks

Chris

**Comment by leovms** [comment]
Hi Chris,

Can you share what is the VM image you are using? What's the OS? It may be related to the following security policy.

**Network access: Do not allow storage of passwords and credentials for network authentication**

Perhaps you can check to see if this option is enabled. If so, can you try disabling it and run the artifact again? It may help us narrow down the root cause.

**Comment by chrispont** [comment]
It seemed to be solved by supplying the full domain name in front of the user with domain join permission. All seems OK now and works perfectly.
