### ISSUE TITLE
Cannot reuse custom Images to create new evironment

### ISSUE THREAD

**Issue by saffiali** [Azure/azure-devtestlab#312]
Steps i followed:
- Copied an existing 4VHD file to DTL
- Created 4 Custom Images based on that
- Created a new [repo ](https://docs.microsoft.com/en-my/azure/devtest-lab/devtest-lab-add-artifact-repo)to create new Environment refrencing the custom images:
"customImageId": "/subscription/xxxxxxxxx"

But when i do that, the i can see the ARM template as one of the vase images, but i deply i got an error:

Sample Resource Template:
`  {
      "apiVersion": "2017-04-26-preview",
      "type": "Microsoft.DevTestLab/labs/virtualmachines",
      "name": "[variables('vmName')]",
      "location": "[resourceGroup().location]",
      "properties": {
        "labVirtualNetworkId": "[variables('labVirtualNetworkId')]",
        "notes": "xxxx-OSDisk",
        "customImageId": "/subscriptions/xxxxxxxx",
        "size": "[parameters('size')]",
        "userName": "[parameters('userName')]",
        "password": "[parameters('password')]",
        "isAuthenticationWithSshKey": false,
        "labSubnetName": "[variables('labSubnetName')]",
        "disallowPublicIpAddress": true,
        "storageType": "Premium",
        "allowClaim": false,
        "networkInterface": {
          "sharedPublicIpAddressConfiguration": {
            "inboundNatRules": [
              {
                "transportProtocol": "tcp",
                "backendPort": 3389
              }
            ]
          }
        }
      }
    }`

**Comment by drwill-ms** [comment]
Hi Saffiali -

One must not specify DTL resources in an ARM template when using the "environment" feature. This is strictly for deploying non-DTL assets.

In order to reference DTL custom images, first fetch the managed image Id from the DTL custom image, and instead refer to that resource in the ARM template.

Sindhu added steps to do this in our MSDN forum. You can find that reply here: https://social.msdn.microsoft.com/Forums/en-US/1093346a-441d-4c29-b079-bf633549375e/how-to?forum=AzureDevTestLabs.

Regards,
David
