### ISSUE TITLE
error loading the template

### ISSUE THREAD

**Issue by RobertKomara** [Azure/azure-devtestlab#342]
I received this notification when trying to deploy this template:

> There was an error loading the template from URI 'https://raw.githubusercontent.com/Azure/azure-devtestlab/master/ARMTemplates/301-dtl-create-lab-with-existing-vnet/azuredeploy.json'. Ensure that the template is publicly accessible and does not have any comments.

Any suggestions as to how to fix it?

**Comment by ajay-arora** [comment]
Hi Robert,

I just deployed this template on one of my resource groups and it worked fine for me.
Can you please describe how you are deploying the ARM template ?
Are you able to deploy other templates from Azure quick start gallery ? (https://azure.microsoft.com/en-us/resources/templates/)

Regards
Ajay

**Comment by RobertKomara** [comment]
Hi Ajay,

I'm just using the deploy button in the readme: https://camo.githubusercontent.com/9285dd3998997a0835869065bb15e5d500475034/687474703a2f2f617a7572656465706c6f792e6e65742f6465706c6f79627574746f6e2e706e67. Deploying this template the same way from here works fine for me: https://github.com/Azure/azure-quickstart-templates/tree/master/101-dtl-create-lab. I am using these examples to demo for a client and want to not have to use PS for now and keep it simple using the deploy buttons. Possibly a problem with the links? Thanks, Robert.

**Comment by ajay-arora** [comment]
The above link just shows a snap of the deploy button. Can you please share the web page link, so that i can understand it fully.

Having said that, I am no expert on this. The link that the Deploy button on github opens is this : https://ms.portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fazure%2Fazure-quickstart-templates%2Fmaster%2F101-dtl-create-lab%2Fazuredeploy.json

Check what link gets opened by the deploy button you open.

**Comment by RobertKomara** [comment]
That link is working fine for me. The create a formula sample is not working with the same error message: https://github.com/Azure/azure-devtestlab/tree/master/Samples/201-dtl-create-formula. Would you mind trying that one by using the deploy button?

**Comment by ross-p-smith** [comment]
The issue is with the Readme.md file. It looks like someone has moved the scripts from the ARMTemplates folder into samples, but not gone through and updated the folder location that sits behind the "Deploy to Azure" button. 

For instance - you look at this file and you will see that the button points to a folder called "ARMTemplates" and not "Samples"
https://raw.githubusercontent.com/Azure/azure-devtestlab/master/Samples/201-dtl-create-formula/README.md

Robert, do something like this in powershell until the repo is fixed up

New-AzureRmResourceGroupDeployment -Name ExampleDeployment -ResourceGroupName ExampleResourceGroup `
  -TemplateUri https://raw.githubusercontent.com/Azure/azure-devtestlab/master/Samples/201-dtl-create-formula/azuredeploy.json `
  -storageAccountType Standard_GRS

**Comment by RobertKomara** [comment]
Thanks Ross!

**Comment by NawazishS** [comment]
Hey, am trying to clone the reo to local machine, customize the script and run the code from my private repository is giving me error "There was an error loading the template from URI 'https://'. Ensure that the template is publicly accessible and does not have any comments". Can yu help me, i need to run this from private repo.

**Comment by leovms** [comment]
@NawazishS, you need to give us more information. Can you provide which template you are working with, what changes you made, and what parameters you are passing to the template?
