### ISSUE TITLE
Webapp w/ MySQL deployment failing

### ISSUE THREAD

**Issue by larryms** [Azure/azure-devtestlab#426]
Deployment of the Webapp with MySQL fails with the error "Gen4 hardware is not supported for this region"

**Comment by codefoster** [comment]
I hit this too because I was following [this](https://docs.microsoft.com/en-us/azure/mysql/quickstart-create-mysql-server-database-using-azure-cli) guide and trying to create it in the `westus` region. I used `GP_Gen5_1` for the sku instead and changed the region to `westus2`, and now I'm getting `The edition  does not support the service objective GP_Gen5_1`. Still working on the right CLI command. Here's what I have so far...
```
az mysql server create --resource-group <myrg> --name <name>  --location westus2 --admin-user myadmin --admin-password <password> --sku-name GP_Gen5_1 --version 5.7
```

**Comment by codefoster** [comment]
Got it working by switching `GP_Gen5_1` to `GP_Gen5_2`. Here's my working command...
```
az mysql server create --resource-group <myrg> --name <name>  --location westus2 --admin-user myadmin --admin-password <password> --sku-name GP_Gen5_2 --version 5.7
```
