### ISSUE TITLE
Pipelines Agent artfact fails with ERROR: Connecting to remote server localhost failed 

### ISSUE THREAD

**Issue by NenoLoje** [Azure/azure-devtestlab#434]
I'm trying to use the [Pipelines Agent artifact](https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-vsts-build-agent) (windows-vsts-build-agent) to setup a new agent.

The artifact installation fails with the following error message:

> Validating parameters
> Preparing agent installation location
> Checking for previously configured agent
> Downloading agent package
> Extracting agent package contents
> Getting agent installer path
> Installing agent
> **ERROR: Connecting to remote server localhost failed with the following error message : The client cannot connect to the destination specified in the request.** Verify that the service on the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig". For more information, see the about_Remote_Troubleshooting Help topic.

Steps to reproduce:
1. Create a new DevTest Lab
2. Create a VM using the template: **Windows 10 Pro, Version 1809 and Size** = `Standard D2 v2 Promo (2 cores, 7 GB memory)`
3. Add the **Pipelines Agent** artifact and supply the required parameters.

Any idea what might be causing this?

Thanks,
--Neno

PS: Screenshot:

![grafik](https://user-images.githubusercontent.com/13981145/53110694-da1a2580-353b-11e9-8d45-53e4a1e1ba94.png)

**Comment by NenoLoje** [comment]
Additional steps to reproduce:
- After some research, it seems that the error only shows up when "Run as auto-logon" parameter of the Pipelines Agent task is set to **true**.
- When set to **false**, the artifact is successfully applied.

**Comment by NenoLoje** [comment]
From looking at the output. the error seems to be thrown by the [Prep-MachineForAutologon](https://github.com/Azure/azure-devtestlab/blob/master/Artifacts/windows-vsts-build-agent/vsts-agent-install.ps1#L237) function.

**Comment by NenoLoje** [comment]
Another observation:
- I tried the same steps using a different base image, this time **[smalldisk] Windows Server 2016 Datacenter** and that works as expected!
- So this seems to be specific to the Windows 10 Pro image.

**Comment by NenoLoje** [comment]
PS: Manually connecting to the Windows 10 machine and configuring the agent works, so it is possibly an issue in the artifact's installation code.

**Comment by DeChrist** [comment]
Hi Leno,

another one you beat me to... I confirm all your previous posts (including specific to Window 10 image).
I have the root cause and a workaround on this one though.
Also, I planned on integrating the workaround in the artifact.

In (repeated) testing the issue is due to the WinRM service not being enabled and running (as hinted by initial error details).

The **workaround** is to have a "`windows-run-powershell`" artifact before the Deployment Group artifact that executes:
`Enable-PSRemoting -SkipNetworkProfileCheck –force`

From [Enable-PSRemoting docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/enable-psremoting?view=powershell-6)

**-SkipNetworkProfileCheck**

- Indicates that this cmdlet enables remoting on client versions of the Windows operating system when the computer is on a public network. This parameter enables a firewall rule for public networks that _allows remote access only from computers in the same local subnet_.
 
- This parameter _does not affect server versions of the Windows operating system_, which, by default, have a local subnet firewall rule for public networks. If the local subnet firewall rule is disabled on a server version, Enable-PSRemoting re-enables it, regardless of the value of this parameter.

This seems to confirm the OS specificity.

Fixing the artifact should entail:

Run the command `Enable-PSRemoting -SkipNetworkProfileCheck –force` only if:
1. OS version is Windows 10
2. The WinRM service is NOT running

**Comment by NenoLoje** [comment]
Thanks, @DeChrist! Indeed, using this workaround agent configuration succeeded, that's cool.
Do you want to create a PR for this?

Curious: why did I not need to enable WinRM, when configuring the agent manually on Win10?

Unfortunately, even with the agent setup now fixed, the agent still does not start properly on Win10 (doesn't show up as '**online**' in Azure DevOps' agent pool) - I created #441 to track this.

--Neno

**Comment by leovms** [comment]
Can you confirm that a reboot would solve this issue without having to add the suggested call to `Enable-PSRemoting`? If so, please look at [this commit](https://github.com/leovms/azure-devtestlab/commit/089266f9fbb61c266e20872e6577ed9058d89855) for the changes that add the restart logic to the `artifactfile.json` file.

**Comment by DeChrist** [comment]
Hi @leovms 

I infer from your fix being a reboot that the fix I proposed earlier is a bit dodgy (being conditional on an edge case).
I agree! This is why I did not pursue the PR (at least without repo owner opinion, which I now have).

I'll leave it to @NenoLoje to confirm if a reboot solves the issue for the '`windows-vsts-build-agent`' artifact.
That is because, the similar problem I have is actually with the other (very similar) artifact "[windows-deploymentgroup](https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-deploymentgroup)".
So possibly you may introduce the same "reboot" after artifact deployment in this other `artifactfile.json` file?

FYI, in my use case, the "`windows-deploymentgroup`" agent is configured as a console app so that interactive tests can be run (vs. as a service). This actually triggers a reboot so autologon and console start can take place. So this is another reboot just after the one in the artifact.

**Comment by NenoLoje** [comment]
Thanks @all, will try and let you know how it goes.

**Comment by leovms** [comment]
Updates have been done to the corresponding artifact. Please retry and re-open, as needed.

**Comment by nikydobrev** [comment]
Hello everyone.

I have the same error when applying artifact "Azure Pipelines Agent"

![Capture](https://user-images.githubusercontent.com/6898714/112982047-ab33fc00-9164-11eb-8ea7-df138b85a0e0.PNG)

Steps to reproduce:

1. Create a new DevTest Lab
2. Create a VM using the template: "Visual Studio 2019 Community (latest release) on Windows Server 2019 (x64)", Size = Standard DS2 v2
3. Add the Pipelines Agent artifact and supply the required parameters.

It only fails if the "Run as auto-login" parameter of the Pipelines Agent task is set to true. If it is set to false the artifact is installed successfully.

Any idea what might be causing this?

Thanks,
--Nikolay
