### ISSUE TITLE
No-op artifact error

### ISSUE THREAD

**Issue by jpcast88** [Azure/azure-devtestlab#511]
Reference https://github.com/Azure/azure-devtestlab/tree/master/Artifacts/windows-noop
No-Op artifact fails with the following error
{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'customScriptArtifact-183362431'. Error message: \"Failed to download all specified files. Exiting. Error Message: The remote name could not be resolved: 'acblab8867.blob.core.windows.net'\"."}]}} The 'No-Op' artifact failed to install. See artifact result for details.

This prevents the Windows-CreateDomain artifact from running/being applied.

**Comment by leovms** [comment]
@jpcast88, the error indicates that the VM is unable to reach the storage account. The No-op artifact happens to be the first in your list, so it will show as the failing artifact. Can you login the VM in question and ensure you can reach that blob or any other URL?

**Comment by jpcast88** [comment]
Thanks @leovms for the help. I found that I had a custom DNS server configured for that VM. 

Also, just curious, how are the No-OP and create domain artifacts tied together? I only added the Create domain artifact to my lab formula and couldn't find how/why the no-op is called prior to running the create domain.

**Comment by leovms** [comment]
Great to hear you found the root cause.

The No-op artifact is automatically injected on Windows VMs the very first time an artifact is applied, up until the time it completes successfully. It does literally nothing more than echo a message. It is used to ensure the sequence of artifacts is respected, as new Windows VMs may undergo an update that can affect applying artifacts and its sequence.

Whenever you see an issue with this artifact, it usually means that some prerequisite for applying artifacts successfully is not functioning correctly. In your particular case, something to do with networking because the artifact runner could not communicate with the storage account it needed.

**Comment by jpcast88** [comment]
Ah I see. Thank you so much for clarifying that for me.

**Comment by sb-31** [comment]
I've got the same problem, and almost the same message. However, I don't have an URL in the error message. Do you have any idea where to look @leovms ?
Error message: 
{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'customScriptArtifact-183362431'. Error message: \"Failed to download all specified files. Exiting. Error Message: The remote server returned an error: (403) Forbidden.\"."}]}}
 
 The 'No-Op' artifact failed to install. See artifact result for details.

**Comment by leovms** [comment]
@sb-31, take a look to see if a new NSG has been added to your lab's virtual network that may be limiting traffic. Another thing to check is if a proxy is in the path that's blocking because of incorrect creds.
