### ISSUE TITLE
There was an error downloading the template from URI

### ISSUE THREAD

**Issue by Deagital** [Azure/azure-devtestlab#570]
Hi,

Could anyone help me why this linked template https://portal.azure.com/#create/Microsoft.Template/uri/http%3A%2F%2Fdeployfreeazure.ingenibridge.com%2Ffiles%2Fazuredeploy.json does not work?

And yet, the azuredeploy file does exist : http://deployfreeazure.ingenibridge.com/files/azuredeploy.json

Thank you, José

**Comment by leovms** [comment]
I don't know what the expectation from the portal's `Microsoft.Template` is, but I would guess that it doesn't like `HTTP` and since the template is not available via `HTTPS`, it cannot reach it. Can you try to make the template available via `HTTPS` and try again?

Having said that, this is not a DTL issue. You will need to request help via the Portal with the `Microsoft.Template` team to do further troubleshooting.
