### ISSUE TITLE
'windows-winrm' Artifact uses hardcoded expiration date  01/01/2022

### ISSUE THREAD

**Issue by Fred-Accruent** [Azure/azure-devtestlab#818]
Hi,

I am using the 'windows-winrm' Artifact.
Its creates a certificate with expiration date 01/01/2022.

Could you please update the expiration date.
Or provide me with a hint to work around the issue.

https://github.com/Azure/azure-devtestlab/blob/e5cee3293098dbc5e3a12235f471ccfb7886c9fd/Artifacts/windows-winrm/config-winrm.ps1#L69

Thanks,
Fred

**Comment by vsantonov** [comment]
If you need short workaround ther's two options. 
1. Disable HTTPS, then you have to use real hostname of VM instead of IP address. 
2. Run `winrm create winrm/config/Listener?Address=*+Transport=HTTPS '@{Hostname="hostname"; CertificateThumbprint="thumbprint"}'` You might need to delete old listener before

**Comment by Fred-Accruent** [comment]
Thanks for the responds.
We created a temporary work around by fixing the issue in a copy of the artifact in a private repository.

**Comment by leovms** [comment]
Artifact has been updated. Please retry and let us know if the issue is now resolved.
