### ISSUE TITLE
DevTest Labs cannot fetch available artifacts

### ISSUE THREAD

**Issue by Chris-Sanford** [Azure/azure-devtestlab#882]
When attempting to configure mandatory artifacts or selecting artifacts to install on a new VM deployment within any of our DevTest Labs, no artifacts are returned in the artifacts list. DevTest Labs that have one or more mandatory artifacts configured return a message stating:

> Virtual machine creation will fail as one or more artifact repositories have been disabled for this lab's mandatory artifact(s). Please re-enable the repository to resolve the issue.

Neither of the repositories have been disabled or deleted. The only repositories we have configured are the 2 default repositories. This is also occurring on a brand new DevTest Lab. This is also happening on 2 separate subscriptions in 2 separate tenants.

**Comment by andrewgbell** [comment]
We are having a similar issue with artifacts, I since Friday, 27th.  I can see a change here:
https://github.com/Azure/azure-devtestlab/commit/88c7ece305b2d003e3324c4a5742160709671b71

Though it may not be the only one.  Our boxes will deploy but the artifacts don't seem to install at all.  The above is one which has worked for some years and stopped working Friday.

**Comment by Chris-Sanford** [comment]
As of October 31st, 2023 it seems artifacts are once again available.
